#%RAML 1.0
title: Course Reserves Roles API
version: v1
protocols: [ HTTP, HTTPS ]
baseUri: http://github.com/org/folio/mod-courses

documentation:
    - title: Course Reserves Roles API
      content: API calls to perform CRUD on instructor roles for courses

types:
    role: !include role.json
    roles: !include roles.json
    errors: !include raml-util/schemas/errors.schema

traits:
    pageable: !include raml-util/traits/pageable.raml
    searchable: !include raml-util/traits/searchable.raml
    language: !include raml-util/traits/language.raml
    validate: !include raml-util/traits/validation.raml

resourceTypes:
    collection: !include raml-util/rtypes/collection.raml
    collection-item: !include raml-util/rtypes/item-collection.raml
    get-delete-only: !include raml-util/rtypes/get-delete.raml

/roles:
    description: "Handle roles for course instructors"
    type:
        collection:
            exampleCollection: !include examples/roles.json
            exampleItem: !include examples/role.json
            schemaCollection: roles
            schemaItem: role
    get:
        description: "Return a list of roles"
        is: [
            searchable: { description: "With valid searchable fields", example: "name=aaa"},
            pageable
        ]
    post:
        description: "Create a new role"
        is: [ validate ]
    delete:
        description: "Delete all roles"
        is: [ validate ]
        responses:
            204:
                description: "All roles deleted"
            500:
                description: "Internal server error"
                body:
                    text/plain:
                        example: "Internal server error"
    /{role_id}:
        description: "With provided role id"
        type:
            collection-item:
                exampleItem: !include examples/role.json
                schema: role
        get:
        put:
            description: "Update a role by id"
            is: [ validate ]
        delete:
