#%RAML 1.0
title: Course Reserves Schedules API
version: v1
protocols: [ HTTP, HTTPS ]
baseUri: http://github.com/org/folio/mod-courses

documentation:
    - title: Course Reserves Schedules API
      content: API calls to perform CRUD on schedules for courses

types:
    schedule: !include schedule.json
    schedules: !include schedules.json
    errors: !include raml-util/schemas/errors.schema

traits:
    pageable: !include raml-util/traits/pageable.raml
    searchable: !include raml-util/traits/searchable.raml
    language: !include raml-util/traits/language.raml
    validate: !include raml-util/traits/validation.raml

resourceTypes:
    collection: !include raml-util/rtypes/collection.raml
    collection-item: !include raml-util/rtypes/item-collection.raml
    get-delete-only: !include raml-util/rtypes/get-delete.raml

/courses:
    /schedules:
        description: "Handle schedules for courses"
        type:
            collection:
                exampleCollection: !include examples/schedules.json
                exampleItem: !include examples/schedule.json
                schemaCollection: schedules
                schemaItem: schedule
        get:
            description: "Return a list of schedules"
            is: [
                searchable: { description: "With valid searchable fields", example: "name=aaa"},
                pageable
            ]
        post:
            description: "Create a new schedule"
            is: [ validate ]
        delete:
            description: "Delete all schedules"
            is: [ validate ]
            responses:
                204:
                    description: "All schedules deleted"
                500:
                    description: "Internal server error"
                    body:
                        text/plain:
                            example: "Internal server error"
        /{schedule_id}:
            description: "With provided schedule id"
            type:
                collection-item:
                    exampleItem: !include examples/schedule.json
                    schema: schedule
            get:
            put:
                description: "Update a schedule by id"
                is: [ validate ]
            delete:
